[package]
name = "punk"
version = "0.1.0"
edition = "2021"

[dependencies]
ymcrust = {git = "https://github.com/Ymclash/ymcrust.git"}
nom = "7.0"
float-derive = "0.1.0"
num-traits = "0.2.14"
num-complex = "0.4.6"
num-bigint = "0.4.6"



[lib]
name = "punk"
path = "src/lib.rs"



[[test]]
name = "lex_test"
path = "tests/lex_test.rs"
[[test]]
name = "lex_indentation_test"
path = "tests/lex_indentation_test.rs"

[[test]]
name = "parse_test"
path = "tests/parser_test.rs"
